db:
  driver: mysql+pymysql
  host: localhost
  port: 3306
  user: testuser
  pass: testp@ss
  name: testdb

rabbitmq:
  host: localhost
  port: 5672
  queue: simcards

log-level: INFO
log-name: SIM-INFO

timeout-request: 0